#redis 配置
spring:
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        #最大连接线程数
        max-active: 10
        #最大空闲连接
        max-idle: 3
        #最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#测试环境
---
spring:
  profiles: test
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        #最大连接线程数
        max-active: 10
        #最大空闲连接
        max-idle: 2
        #最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
#生产环境
---
spring:
  profiles: release
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    jedis:
      pool:
        #最大连接线程数
        max-active: 10
        #最大空闲连接
        max-idle: 2
        #最小空闲连接
        min-idle: 2
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
